version: '3'
services:
  app:
    build:
      context: .
      args:
        - VUE_APP_SECURE=$VUE_APP_SECURE
        - VUE_APP_BASE_API=$VUE_APP_BASE_API
        - VUE_APP_BASE_API_PORT=$VUE_APP_BASE_API_PORT
        - VUE_APP_SECRET_CLIENT_GOOGLE=$VUE_APP_SECRET_CLIENT_GOOGLE
    ports:
      - 8080:80
    env_file:
      - .env