version: '2.4'
services:
  picassoadmin: 
    build: 
      context: .
      dockerfile: Dockerfile.staging
    #ports: 
    #  - "8080:8080"
    mem_limit: 1024m
    mem_reservation: 128m
    cpus: 1
    networks: 
      - gateway
    environment: 
      COMPOSE_PROJECT_NAME: picasso-admin-staging

networks: 
  gateway:
    external: true
    